import globals from "globals";
import js from "@eslint/js";
import stylistic from "@stylistic/eslint-plugin-js";

export default [
    {
        "languageOptions":
        {
            "globals":
            {
                ...globals.browser,
                ...globals.node,
            },
        },
        "plugins": {
            "@stylistic": stylistic,
        },
        "rules": {
            "@stylistic/array-bracket-newline": [ "error", { "multiline": true } ],
            "@stylistic/array-bracket-spacing": [ "error", "always" ],
            "@stylistic/array-element-newline": [ "error", { "multiline": true } ],
            "@stylistic/arrow-parens": [ "error", "always" ],
            "@stylistic/arrow-spacing": "error",
            "@stylistic/block-spacing": "error",
            "@stylistic/brace-style": [ "error", "1tbs", { "allowSingleLine": true } ],
            "@stylistic/comma-dangle": [ "error", "always-multiline" ],
            "@stylistic/comma-spacing": [ "error", { "before": false, "after": true } ],
            "@stylistic/comma-style": [ "error", "last" ],
            "@stylistic/computed-property-spacing": [ "error", "never" ],
            "@stylistic/dot-location": [ "error", "object" ],
            "@stylistic/eol-last": [ "error", "always" ],
            "@stylistic/func-call-spacing": "error",
            "@stylistic/function-call-argument-newline": [ "error", "never" ],
            "@stylistic/function-call-spacing": [ "error", "never" ],
            "@stylistic/function-paren-newline": [ "error", "never" ],
            "@stylistic/generator-star-spacing": [ "error", { "before": true, "after": true } ],
            "@stylistic/implicit-arrow-linebreak": [ "error", "beside" ],
            "@stylistic/indent": [ "error", 4 ],
            "@stylistic/jsx-quotes": [ "error", "prefer-double" ],
            "@stylistic/key-spacing": [ "error", { "afterColon": true } ],
            "@stylistic/keyword-spacing": "error",
            "@stylistic/line-comment-position": [ "error", { "position": "above" } ],
            "@stylistic/linebreak-style": [ "error", "unix" ],
            "@stylistic/lines-around-comment": [ "error", { "beforeBlockComment": true } ],
            "@stylistic/lines-between-class-members": "error",
            "@stylistic/max-statements-per-line": [ "error", { "max": 4 } ],
            "@stylistic/multiline-comment-style": [ "error", "starred-block" ],
            "@stylistic/multiline-ternary": [ "error", "never" ],
            "@stylistic/new-parens": [ "error", "never" ],
            "@stylistic/newline-per-chained-call": [ "error", { "ignoreChainWithDepth": 2 } ],
            "@stylistic/no-confusing-arrow": "error",
            "@stylistic/no-extra-parens": [ "error", "all" ],
            "@stylistic/no-extra-semi": "error",
            "@stylistic/no-floating-decimal": "error",
            "@stylistic/no-mixed-operators": "error",
            "@stylistic/no-mixed-spaces-and-tabs": "error",
            "@stylistic/no-multi-spaces": "error",
            "@stylistic/no-multiple-empty-lines": "error",
            "@stylistic/no-tabs": "error",
            "@stylistic/no-trailing-spaces": "error",
            "@stylistic/no-whitespace-before-property": "error",
            "@stylistic/nonblock-statement-body-position": "error",
            "@stylistic/object-curly-spacing": [ "error", "always" ],
            "@stylistic/one-var-declaration-per-line": "error",
            "@stylistic/quote-props": [ "error", "always" ],
            "@stylistic/quotes": [ "error", "double" ],
            "@stylistic/rest-spread-spacing": [ "error", "never" ],
            "@stylistic/semi": "error",
            "@stylistic/semi-spacing": [ "error", { "before": false, "after": true } ],
            "@stylistic/semi-style": [ "error", "last" ],
            "@stylistic/space-before-blocks": "error",
            "@stylistic/space-before-function-paren": [ "error", { "anonymous": "always", "named": "never", "asyncArrow": "always" } ],
            "@stylistic/space-in-parens": "error",
            "@stylistic/space-infix-ops": "error",
            "@stylistic/space-unary-ops": "error",
            "@stylistic/spaced-comment": [ "error", "always" ],
            "@stylistic/switch-colon-spacing": [ "error", { "before": false, "after": true } ],
            "@stylistic/template-curly-spacing": "error",
            "@stylistic/template-tag-spacing": "error",
            "@stylistic/wrap-iife": [ "error", "inside" ],
            "@stylistic/wrap-regex": "error",
            "@stylistic/yield-star-spacing": [ "error", "both" ],
        },
    },
    js.configs.recommended,
];
