name: Publish
on:
  workflow_dispatch:
  release:
      types: [published]

jobs:
  verify:
    name: Publish Package to Registry
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          registry-url: 'https://registry.npmjs.org'
      - name: Publish Package
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
